#UPPER SERVE PARA DEIXAR TODAS AS LETRAS MAIÚSCULAS
print("Joana".upper())

#LOWER SERVE PARA DEIXAR TODAS AS LETRAS MINÚSCULAS
print("JOANA".lower())

#DEIXAR APENAS A PRIMEIRA MAIÚSCULA E AS DEMAIS MINÚSCULAS
print("joana".title())